import './globals.css';
import type { Metadata } from 'next';
import { primary } from '@/fonts';
import { PropsWithChildren } from 'react';
import clsx from 'clsx';
import { Toaster } from '@/components/ui/sonner';
import { Header } from './(layout)/header';
import { Footer } from './(layout)/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={clsx(primary.variable, 'font-primary')}>
        <Header menuLinks={[]} />
        {children}
        <Toaster />
        <Footer menuLinks={[]} />
      </body>
    </html>
  );
}
