import './globals.css';
import type { Metadata } from 'next';
import { primary } from '@/fonts';
import { PropsWithChildren } from 'react';
import { Toaster } from '@/components/ui/sonner';
import { Header } from './(layout)/header';
import { Footer } from './(layout)/footer';
import { cn } from '@/lib/shadcn/utils';
import { headerProps } from './(layout)/header/story-props';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body
        className={cn(
          primary.variable,
          'font-primary text-[1rem]/[1.5] text-black'
        )}
      >
        <Header {...headerProps} />
        {children}
        <Footer menuLinks={[]} />
        <Toaster />
      </body>
    </html>
  );
}
